update gitlab pipeline uninstall-okd-feature

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -142,16 +142,10 @@ uninstall-okd-feature:
   stage: uninstall-okd-feature
   image: gitlab.isdd.sk:4567/isdd-docker/base-images/kubectl-delivery:1-0-0
   script:
-    - echo "Checking for Helm release for feature branch..."
+    - echo "Attempting to clean up Helm release for feature branch..."
     - oc login --token=$OKD_TOKEN --server=https://api.dev.isdd.sk:6443
     - RELEASE_NAME=$(echo $CI_COMMIT_REF_NAME | sed 's/\//-/g' | tr '[:upper:]' '[:lower:]')
-    - |
-      if helm ls -n metais3 | grep -q "$RELEASE_NAME"; then
-        echo "Helm release $RELEASE_NAME found, uninstalling..."
-        helm uninstall "$RELEASE_NAME" -n metais3
-      else
-        echo "Helm release $RELEASE_NAME not found, skipping uninstallation."
-      fi
+    - helm uninstall "$RELEASE_NAME" -n metais3 || echo "Helm release $RELEASE_NAME not found, or already uninstalled."
   rules:
     - if: $CI_COMMIT_REF_NAME =~ /^feature\/.+$/ && $CI_PIPELINE_SOURCE == "merge_request_event"
       when: manual
